language: java
#rvm:
# - 2.2
# - jruby
# - rbx-3

sudo: false
install: true

dist: trusty

# addons:
#    apt:
#      update: true
addons:
    sonarcloud:
        organization: "sunnypanda-github"
        token:
          secure: "b62d3dcc518e6311fcf14f1625ac5b38ae8c061e"
    script:
      # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
      - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

      jdk:
        - oraclejdk8