language: java
dist: trusty
sudo: false
install: true

addons:
    apt:
        update: true
    sonarcloud:
        organization: "sunnypanda-github"
        token:
          secure: "b62d3dcc518e6311fcf14f1625ac5b38ae8c061e"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
