INSERT INTO DRIVER (PERSONAL_NUMBER, FIRST_NAME, LAST_NAME) VALUES ('34098753', 'Аркадий', 'Исааков');
INSERT INTO DRIVER (PERSONAL_NUMBER, FIRST_NAME, LAST_NAME) VALUES ('56084545', 'Вениамин', 'Пунктуальный');
INSERT INTO DRIVER (PERSONAL_NUMBER, FIRST_NAME, LAST_NAME) VALUES ('49853098', 'Варвара', 'Полякова');
INSERT INTO DRIVER (PERSONAL_NUMBER, FIRST_NAME, LAST_NAME) VALUES ('69384023', 'Клюква', 'Песочная');
INSERT INTO DRIVER (PERSONAL_NUMBER, FIRST_NAME, LAST_NAME) VALUES ('50948503', 'Елена', 'Парная');

INSERT INTO TRUCK (REG_NUMBER, SHIFT_SIZE, CAPACITY) VALUES ('GH57384', '2', '35');
INSERT INTO TRUCK (REG_NUMBER, SHIFT_SIZE, CAPACITY) VALUES ('FE78430', '1', '100');
INSERT INTO TRUCK (REG_NUMBER, SHIFT_SIZE, CAPACITY) VALUES ('BJ50984', '2', '3');
INSERT INTO TRUCK (REG_NUMBER, SHIFT_SIZE, CAPACITY) VALUES ('YU74801', '3', '76');
INSERT INTO TRUCK (REG_NUMBER, SHIFT_SIZE, CAPACITY) VALUES ('SG87048', '2', '200');

