CREATE TABLE DRIVER(
  DRIVER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  PERSONAL_NUMBER INT,
  FIRST_NAME VARCHAR(45),
  LAST_NAME VARCHAR(45),
--   HOURS_PER_MONTH INT,
--   CITY_ID BIGINT NOT NULL,
--   TRUCK_ID BIGINT NOT NULL
);
-- ALTER TABLE DRIVER ADD COLUMN STATUS ENUM('rest', 'in shifts', 'behind the wheel') DEFAULT 'rest';
-- ALTER TABLE DRIVER ADD FOREIGN KEY (TRUCK_ID) REFERENCES TRUCK(TRUCK_ID);

CREATE TABLE TRUCK(
  TRUCK_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  REG_NUMBER VARCHAR(7) NOT NULL,
  SHIFT_SIZE INT,
  CAPACITY INT,
--   CITY_ID BIGINT NOT NULL
);
-- ALTER TABLE TRUCK ADD COLUMN STATE ENUM('functioning', 'defective') DEFAULT 'rest';

-- CREATE TABLE ORDER(
--   ORDER_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
--   UNIQUE_NUMBER INT NOT NULL,
--   DRIVER_ID BIGINT NOT NULL,
--   TRUCK_ID BIGINT NOT NULL,
-- );
-- ALTER TABLE ORDER ADD FOREIGN KEY (TRUCK_ID) REFERENCES TRUCK(TRUCK_ID);


-- CREATE INDEX IDX_RES_DATE_ ON RESERVATION(RES_DATE);
